### ISSUE TITLE
AltJIT not working (URL Developer disk Image)

### ISSUE THREAD

**Issue by vangelis2023aa** [altstoreio/AltStore#1317]
Hey,

I tried applying AltJIT to pojavlauncher today and it failed saying "JIT could not be enabled for PojavLauncher.
                                                                                                             The URL to download the Developer disk 																               image could not be determined."                                                                                                                 
And when i clicked on more details it said "AltServer.DeveloperDiskError 0" on the top and completely below it said Source line:"150". (Source file: Altserver/DeveloperDiskManager.swift) I am on the latest stable altstore and altserver version and I tried enabling JIT many times with the same result as I said above. I also had the mail app open with the plugin. I tried everything what was said in your guide with pymobiledevice3. I hope you guys can fix this.

With kind regards, 
Vangelis

**Comment by harrobe123** [comment]
have same issue please help

**Comment by joshuajohncohen** [comment]
Same here!

**Comment by rama0dev** [comment]
same 😢

**Comment by harrrobe** [comment]
Hi this error only occures on devices with iOS/iPados 1.17.0 and higher. There is a detailed way to do fix this with [this](https://www.reddit.com/r/AltStore/s/EGAlY292Qx) Mac only way. There is a fork of altstore called side store which refreshes via a vpn and has a way that works with windows and Mac to activate JIT.  

To get jit going( on side store) (run this in an admin terminal if you're on Windows)

python3 -m venv venv

# If you're on macOS/Linux
. ./venv/bin/activate
# If you're on Windows using PowerShell
.\venv\Scripts\Activate.ps1
# CMD
.\venv\Scripts\Activate.bat

# All
pip3 install -r requirements.txt
# Windows
.\venv\Scripts\python3.exe main.py
# macOS
sudo python3 -m SideJITServer --help
Or with PyPI:

python3 -m venv venv
# Activate venv..

pip3 install SideJITServer
SideJITServer --help
Here is the [Shortcut](https://www.icloud.com/shortcuts/b0ffc9c3f0e74e7a8f8052c89fa322cf) that goes along with this.

**Comment by Emilgoo** [comment]
(venv) C:\Users\emilgoo\SideJITServer>SideJITServer --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\emilgoo\SideJITServer\venv\Scripts\SideJITServer.exe\__main__.py", line 4, in <module>
  File "C:\Users\emilgoo\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 22, in <module>
    from pymobiledevice3.services.mobile_image_mounter import auto_mount_personalized
  File "C:\Users\emilgoo\SideJITServer\venv\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 15, in <module>
    from pymobiledevice3.restore.tss import TSSRequest
  File "C:\Users\emilgoo\SideJITServer\venv\Lib\site-packages\pymobiledevice3\restore\tss.py", line 10, in <module>
    from ipsw_parser.img4 import COMPONENT_FOURCC
ModuleNotFoundError: No module named 'ipsw_parser.img4'
