### ISSUE TITLE
The process 'altjit' failed with code 1. Could not connect to device . The process 'python3' returned unexpected output. KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')

### ISSUE THREAD

**Issue by jaydenchan1027** [altstoreio/AltStore#1380]
Im in ios 17.4 beta with mac running macos 14.2 I tried everything but it won't work at all

**Comment by larsdante** [comment]
> Im in ios 17.4 beta with mac running macos 14.2 I tried everything but it won't work at all

same here, AltStore also crashes on launch in 17.4 beta

**Comment by dylanchapell** [comment]
I am experiencing this error on iOS 17.3. I installed the dependencies through Xcode with `/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install -U pymobiledevice3==2.30.0 construct==2.10.6`

**Comment by deargosep** [comment]
Happens to me on ios 17.2.1

**Comment by RockChinQ** [comment]
Same issue, running iPad OS 17.3.1 on iPad Air 5. Using AltServer on MacOS Sonoma.

**Comment by hyhcrh** [comment]
Same issue, running iPadOS 17.3 on iPad Pro 2022. Alt server is installed on macOS Ventura.

**Comment by psiberfunk** [comment]
Also having this happen , blew away my homebrew and fully reinstalled brew environment according to instructions.. making sure I have OpenSSL3 and the proper versions of the pymobiledevice/construct tooling:

`brew install openssl@3`
`python3 -m pip install pymobiledevice3==2.30.0 construct==2.10.69`

Running macos 14.4.1 (23E224) on an M3 mac (arm) /   iOS  17.4.1

From my mac I selected "enable JIT" for UTM.. it asks for my mac password.. works for a couple of seconds.. and then dumps this:

Detailed error dump below:

```
Error Description
The process 'altjit' failed with code 1. Could not connect to device 00008110-000538693638801E. The process 'python3' returned unexpected output. KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')

Failure Reason
The process 'altjit' failed with code 1. Could not connect to device 00008110-000538693638801E. The process 'python3' returned unexpected output. KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')

Title
JIT could not be enabled for UTM.

Source Line
61

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
/Users/aless/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 148, in <module>
    main()
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 108, in wrapper
    func(*args, **kwargs)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 591, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 581, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 212, in connect
    if not self._validate_pairing():
  File "/Users/aless/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 453, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')

❌ Unable to enable JIT for UTM on device 00008110-000538693638801E.
Could not connect to device 00008110-000538693638801E. The process 'python3' returned unexpected output. KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
```

**Comment by orhid** [comment]
same here iPadOS 17.5 (21F5048f) and Alt Server on Sonoma 14.4.1 (23E224)

**Comment by psiberfunk** [comment]
@shanegillio anything on this ?  Kinda game breaking..

**Comment by shinmorisawa** [comment]
bro same problem with ipad air running 17.2 with sonoma. :/

**Comment by cgorms** [comment]
Same here on 17.5 RC

**Comment by wandbrandon** [comment]
same here, 17.5

**Comment by ChristianKilduff** [comment]
facing same issue

**Comment by SpyterDev** [comment]
I was facing this same error, I'm on Mac OS 14.4, the target device was a iPad gen 9 on iOS 17.5.1 also the xcode (15.4) python version was 3.9

**Comment by tonycoco** [comment]
Just run the Python yourself.

https://gist.github.com/tonycoco/66b08eea237ff64bf7becb54afb2e04d

**Comment by psiberfunk** [comment]
> Just run the Python yourself.
> 
> https://gist.github.com/tonycoco/66b08eea237ff64bf7becb54afb2e04d

This hardly seems like a good solution to the core problem:  The app has a menu item that's just plain broken on many macs.  I'm not quite sure why the issue is getting ignored.

**Comment by aabdellah** [comment]
any workaround available to use the menu item?

**Comment by ckyuex** [comment]
How to solve this

**Comment by apollovy** [comment]
> Just run the Python yourself.
> 
> [gist.github.com/tonycoco/66b08eea237ff64bf7becb54afb2e04d](https://gist.github.com/tonycoco/66b08eea237ff64bf7becb54afb2e04d)

Thank you very much, the comment in your gist helped to resolve the issue:
> If you're using AltStore you can just make sure you install the dependencies to the Python install that Xcode uses:

> /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install -U pymobiledevice3==2.30.0 construct==2.10.69 qh3==0.15.1

**Comment by orailnoor** [comment]
I just uploaded a video on youtube showing how to enable JIT on iOS 26 using Stik Debug. Watch it here: https://youtu.be/5F5GDwRHAec
